swagger: "2.0"
info:
  description: "this is the swagger documentation for Petemoon project's APIs"
  version: "1.0.0"
  title: "Petemoon API"
host: "petemoon.com"
schemes:
  - "http"
  - "https"
paths:
  /accounts/otp:
    $ref: "accounts/send_otp.yaml"
