# Generated by Django 4.1.4 on 2022-12-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_owner_pet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
