# Generated by Django 4.1.4 on 2023-01-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_pet_photo_alter_pet_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_category', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.petcategory'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pettype'),
        ),
    ]
