# Generated by Django 4.1.4 on 2023-01-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_petcategory_pettype_remove_pet_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcategory',
            name='pet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.pettype'),
        ),
    ]
