
get:
  operationId: cart_get_cart
  summary: get shopping carts products
  description: ''
  parameters: 
  responses:
    200:
        schema:
          $ref: "#/definitions/GetCart"
  tags:
    - cart

post:
  operationId: cart_add_product
  summary: "add products to cart"

  description: ''
  parameters:
  - in: "body"
    name: "body"
    description: "add product"
    required: true
    schema:
      $ref: "#/definitions/PostCart"
  responses:
    200:
      description: 'address added successfuly'

  tags:
    - cart

definitions:
  GetCart:
    type: "object"
    properties:
        success: 
          example: true
        data:
          example:
          - id: 2
            price: 333
            price_after_sale: 3
            petshop: pet shopekabar
            picture:
            count: 2
            products_accumulative_price: 666
          - total_price: 666
  PostCart:
      type: "object"
      properties:
        id: 
          example: 2
          type: "int"
        count:
          example: 2
          type: "int"


